# Exercise 1 from Zed Shaw's Learn Python 3 The Hard Way

print("Hello World!")
print("")
print("Hello Again")
print("")
print("I like typing this.")
print("")
print("This is fun.")
print("")
print('Yay! Printing.')
print("")
print("I'd much rather you 'not'.")
print("")
print('I "said" do not touch this.')
print("")
# print("This should not print, it is commented out")
